import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "@next/font/local";

const arrayFont = localFont({
  src: [
    { path: '../../public/fonts/Array/Array-Regular.woff2', weight: '400'},
    { path: '../../public/fonts/Array/Array-Bold.woff2', weight: '700'},
    { path: '../../public/fonts/Array/Array-Semibold.woff2', weight: '600'},
    { path: '../../public/fonts/Array/Array-Wide.woff2', weight: '400'},
    { path: '../../public/fonts/Array/Array-BoldWide.woff2', weight: '700'},
    { path: '../../public/fonts/Array/Array-SemiboldWide.woff2', weight: '600'},
  ],
  variable: '--font-array',
  display: 'swap',
});

// const array = localFont({
//   src: "../fonts/Array/Array-Semi"
// })

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
