when:
  event: pull_request

steps:
  build:
    image: codeberg.org/woodpecker-plugins/node-pm:1.3.6
    when:
      - event: pull_request
        branch: main
        repo: travisfriesen/travisfriesen.ca
    settings:
      run: build # script name
      with: bun # if `with` is set, enforce to use this package manager
      frozen_lockfile: true # recommended
      ignore_node_modules: true # recommended
