name: Build Docker Container

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string

env:
  IMAGE_NAME: ${{ inputs.IMAGE_NAME }}

jobs:
  build-and-save-docker-image:
    name: Build Docker image and save as artifact
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Save Docker image
        run: |
          mkdir -p image-artifact
          docker save ${{ env.IMAGE_NAME }}:latest > image-artifact/docker-image.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image-artifact/docker-image.tar
          retention-days: 1