name: Build Docker Container

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string

env:
  IMAGE_NAME: ${{ inputs.IMAGE_NAME }}

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to Github Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      ## https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      ## https://github.com/docker/build-push-action
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      ## https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          provenance: false
          context: .
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
             ghcr.io/${{ env.IMAGE_NAME }}:latest

      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}
