name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - release
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build_container.yml
    secrets: inherit
    with:
      IMAGE_NAME: ${{ github.repository }}

  set-port:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      PORT: ${{ steps.set-port.outputs.PORT }}
    steps:
      - name: Set port based on branch
        id: set-port
        run: |
          if [[ "${GITHUB_REF##*/}" == "release" ]]; then
            echo "PORT=80" >> $GITHUB_OUTPUT
          else
            echo "PORT=3000" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: set-port
    uses: ./.github/workflows/deploy_to_oracle_cloud.yml
    with:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      PORT: ${{ needs.set-port.outputs.PORT }}
