name: CI/CD Pipeline

permissions:
  contents: read
  packages: write
  id-token: write

on:
  push:
    branches:
      - main
      - release
  workflow_dispatch:

env:
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build:
    uses: ./.github/workflows/build_container.yml
    secrets: inherit
    with:
      IMAGE_NAME: ${{ github.repository }}

  set-port:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      PORT: ${{ steps.set-port.outputs.PORT }}
    steps:
      - name: Set port based on branch
        id: set-port
        run: |
          if [[ "${GITHUB_REF##*/}" == "release" ]]; then
            echo "ENVIRONMENT=zeus-production" >> $GITHUB_OUTPUT
          else
            echo "PORT=3000" >> $GITHUB_OUTPUT
            echo "ENVIRONMENT=zeus-preview" >> $GITHUB_OUTPUT
          fi

  deploy-production:
    needs: set-port
    if: ${{ needs.set-port.outputs.ENVIRONMENT == 'zeus-production' }}
    uses: ./.github/workflows/deploy_to_oracle_cloud.yml
    with:
      SSH_HOST: $env.SSH_HOST
      SSH_USER: $env.SSH_USER
      SSH_PRIVATE_KEY: $env.SSH_PRIVATE_KEY
      PORT: 80
    environment: zeus-production

  deploy-preview:
    needs: set-port
    if: ${{ needs.set-port.outputs.ENVIRONMENT == 'zeus-preview' }}
    uses: ./.github/workflows/deploy_to_oracle_cloud.yml
    with:
      SSH_HOST: $env.SSH_HOST
      SSH_USER: $env.SSH_USER
      SSH_PRIVATE_KEY: $env.SSH_PRIVATE_KEY
      PORT: ${{ needs.set-port.outputs.PORT }}
    environment: zeus-preview