name: CI/CD Pipeline

permissions:
  contents: read
  packages: write
  id-token: write

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - release
  workflow_dispatch:

env:
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    outputs:
      skip-build: ${{ steps.check.outputs.skip-build }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check if build should be skipped
        id: check
        run: |
          if git log -1 --pretty=%B | grep -q '\[skip build\]'; then
            echo "skip-build=true" >> $GITHUB_OUTPUT
          else
            echo "skip-build=false" >> $GITHUB_OUTPUT
          fi

  set-port:
    runs-on: ubuntu-latest
    needs: check-commit-message
    outputs:
      PORT: ${{ steps.set-port.outputs.PORT }}
      ENVIRONMENT: ${{ steps.set-port.outputs.ENVIRONMENT }}
      ENV_URL: ${{ steps.set-port.outputs.ENV_URL }}
      IMAGE_NAME: ${{ steps.set-port.outputs.IMAGE_NAME }}
    steps:
      - name: Set port based on branch
        id: set-port
        run: |
          if [[ "${GITHUB_REF##*/}" == "release" ]]; then
            echo "PORT=80" >> $GITHUB_OUTPUT
            echo "ENVIRONMENT=zeus-production" >> $GITHUB_OUTPUT
            echo "ENV_URL=https://travisfriesen.ca" >> $GITHUB_OUTPUT
            echo "IMAGE_NAME=tf.ca-zeus-production" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "pull_request" && "${{ github.base_ref }}" == "release" ]]; then
            echo "PORT=4000" >> $GITHUB_OUTPUT
            echo "ENVIRONMENT=zeus-staging" >> $GITHUB_OUTPUT
            echo "ENV_URL=https://staging.travisfriesen.travisf.ca" >> $GITHUB_OUTPUT
            echo "IMAGE_NAME=tf.ca-zeus-staging" >> $GITHUB_OUTPUT
          else
            echo "PORT=3000" >> $GITHUB_OUTPUT
            echo "ENVIRONMENT=zeus-preview" >> $GITHUB_OUTPUT
            echo "ENV_URL=https://preview.travisfriesen.travisf.ca" >> $GITHUB_OUTPUT
            echo "IMAGE_NAME=tf.ca-zeus-preview" >> $GITHUB_OUTPUT
          fi
      - name: Debug outputs
        run: |
          echo "PORT: ${{ steps.set-port.outputs.PORT }}"
          echo "ENVIRONMENT: ${{ steps.set-port.outputs.ENVIRONMENT }}"
          echo "ENV_URL: ${{ steps.set-port.outputs.ENV_URL }}"
          echo "IMAGE_NAME: ${{ steps.set-port.outputs.IMAGE_NAME }}"

  build:
    needs: set-port
    if: ${{ needs.check-commit-message.outputs.skip-build != 'true' }}
    uses: ./.github/workflows/build_container.yml
    secrets: inherit
    with:
      IMAGE_NAME: ${{ needs.set-port.outputs.IMAGE_NAME }}

  deploy:
    needs: [set-port, build]
    if: ${{ always() && needs.set-port.result != 'failure' && needs.build.result == 'success' }}
    uses: ./.github/workflows/deploy_to_oracle_cloud.yml
    with:
      PORT: ${{ needs.set-port.outputs.PORT }}
      ENVIRONMENT: ${{ needs.set-port.outputs.ENVIRONMENT }}
      ENV_URL: ${{ needs.set-port.outputs.ENV_URL }}