name: Run Ansible Playbook

on:
  workflow_call:
    inputs:
      PORT:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      ENV_URL:
        required: true
        type: string

jobs:
  ansible:
    runs-on: self-hosted
    environment:
      name: ${{ inputs.ENVIRONMENT }}
      url: ${{ inputs.ENV_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: /tmp/${{ inputs.ENVIRONMENT }}

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          ansible-playbook -i localhost, .github/workflows/ansible_deploy_container.yml --user ubuntu --extra-vars "port=${{ inputs.PORT }} container_name=tfca_container-${{ inputs.ENVIRONMENT }} image_name=tf.ca-${{ inputs.ENVIRONMENT }} artifact_path=/tmp/${{ inputs.ENVIRONMENT }}/docker-image.tar"